name: env_tsanomaly
dependencies:
  - python=3.7
  - pip
  - pandas
  #- jupyter    # for use in Jupyter notebook
  #- ipykernel   # for recognition of conda env in Jupyter notebook
  - pip:
  #  # for regular pip packages
    - matplotlib==3.5.2
    - streamlit==1.0
    - importlib  
    - adtk==0.5.5
    - DateTime==4.3
    #- itsdangerous==0.24
    #- MarkupSafe==1.1.1
    - seaborn==0.11.0   # for multiple displots 
    - scipy
    - PyAstronomy==0.14.0
    - PyYAML==5.1
    - ruamel-yaml==0.15.46
    - patsy==0.5.0
    - openpyxl
    #- psycopg2-binary==2.8.6
    #- sqlalchemy
    - msgpack==0.5.6
    - holidays
    - isoweek==1.3.3
    - textdistance==4.2.0
    #- Pweave==0.30.3
    #- jupyter_client==5.3.1   # needed in conjunction with pweave version
    #- pyod==0.7.7.1
    - nltk==3.4.4
    - werkzeug==0.12.2
    - joblib==1.0.0
    - xlsxwriter==1.3.6
    - xlrd==1.2.0
    - tqdm