name: env_tsanomaly
dependencies:
  - python=3.7
  - pip
  - adtk==0.5.5
  - streamlit==1.13.*
  #- jupyter    # for use in Jupyter notebook
  #- ipykernel   # for recognition of conda env in Jupyter notebook
  - pip:
    - DateTime==4.3
    - seaborn==0.11.*  
    - PyAstronomy==0.14.*
    - PyYAML==5.1
    - ruamel-yaml==0.15.*
    - patsy==0.5.0
    - openpyxl==3.0.10
    - msgpack==0.5.6
    - holidays==0.16
    - isoweek==1.3.3
    - textdistance==4.*
    - nltk==3.4.*
    - joblib==1.0.*
    - xlsxwriter==1.3.6
    - xlrd==1.2.0
    - tqdm
